spring.application.name=frontend-service
server.port=8080
server.forward-headers-strategy=framework
marketplace.api.base-url=${MARKETPLACE_API_BASE_URL:http://api-gateway/api}
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
